CREATE DATABASE IF NOT EXISTS `padel_db`;
GRANT ALL PRIVILEGES ON padel_db.* TO 'root'@'localhost';
FLUSH PRIVILEGES;

USE `padel_db`;

DROP TABLE IF EXISTS `players`;
DROP TABLE IF EXISTS `matches`;

CREATE TABLE IF NOT EXISTS `players` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `nome` VARCHAR(100) NOT NULL,
  `sesso` ENUM('MALE','FEMALE') NOT NULL,
  `livello` FLOAT NOT NULL CHECK (`livello` BETWEEN 0 AND 4),
  `preferred_slot` ENUM('MATTINA','POMERIGGIO','SERA') NULL,
  `email` VARCHAR(255) UNIQUE NOT NULL,
  `telefono` VARCHAR(20),
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `matches` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `player_ids` JSON NOT NULL,
  `orario` DATETIME NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;